name: .NET Core Application CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
  
  
  deploy:
    runs-on: windows-latest
    needs: build  # Ensure the build job completes first

    steps:
      - name: Download publish artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: ./publish

      - name: Install Web Deploy
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/6/D/1/6D1B99FF-5694-4A39-83B7-0B3C74B8400E/WebDeploy_amd64_en.exe" -OutFile "WebDeploy_amd64_en.exe"
          Start-Process -FilePath "WebDeploy_amd64_en.exe" -ArgumentList "/quiet" -NoNewWindow -Wait
      - name: IIS Deploy
        uses: ChristopheLav/iis-deploy@v1.0.0
        with:
          # IIS website name
          website-name: hello-app
          # MS Deploy Service URL
          msdeploy-service-url: https://IIS-Server:8172/msdeploy.axd  # e.g., `https://your-server:8172/msdeploy.axd`
          # Username for Basic authentication to the MS Deploy Service
          msdeploy-username: admin-user
          # Password for Basic authentication to the MS Deploy Service
          msdeploy-password: Pakistan@1234
          # The path to the source directory that will be deployed
          source-path: ./publish
