name: .NET Core Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download publish artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: ./publish

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: 'ftp://57.154.178.209'  # Your FTP server address
          username: 'win-admin'             # Your FTP username
          password: 'PWf%vrvrQwsn@1234'     # Your FTP password
          local-dir: './publish/'            # Local directory to upload
          server-dir: 'C:/IIS-Task-main/'    # Remote directory on FTP server
